sudo: false
language: ruby
rvm:
  - 2.3.3
  - 2.4.2
  - 2.5.0
  - jruby
before_install: gem install bundler -v 1.14.6
gemfile:
  - gemfiles/ci.gemfile
addons:
  postgresql: "9.6"
services:
  - postgresql
